# Copyright (C) 2011-2013 The CyanogenMod Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/samsung/delos3geur/setup-makefiles.sh

PRODUCT_COPY_FILES += \
	vendor/samsung/delos3geur/proprietary/bin/btnvtool:system/bin/btnvtool \
	vendor/samsung/delos3geur/proprietary/bin/ds_fmc_appd:system/bin/ds_fmc_appd \
	vendor/samsung/delos3geur/proprietary/bin/e2fsck:system/bin/e2fsck \
	vendor/samsung/delos3geur/proprietary/bin/fmconfig:system/bin/fmconfig \
	vendor/samsung/delos3geur/proprietary/bin/hci_qcomm_init:system/bin/hci_qcomm_init \
	vendor/samsung/delos3geur/proprietary/bin/mpdecision:system/bin/mpdecision \
	vendor/samsung/delos3geur/proprietary/bin/netmgrd:system/bin/netmgrd \
	vendor/samsung/delos3geur/proprietary/bin/qmuxd:system/bin/qmuxd \
	vendor/samsung/delos3geur/proprietary/bin/rmt_storage:system/bin/rmt_storage \
	vendor/samsung/delos3geur/proprietary/bin/thermald:system/bin/thermald \
	vendor/samsung/delos3geur/proprietary/bin/usbhub:system/bin/usbhub \
	vendor/samsung/delos3geur/proprietary/bin/usbhub_init:system/usbhub_init \
	vendor/samsung/delos3geur/proprietary/etc/firmware/ath6k/AR6003/hw2.1.1/athtcmd_ram.bin:system/etc/firmware/ath6k/AR6003/hw2.1.1/athtcmd_ram.bin \
	vendor/samsung/delos3geur/proprietary/etc/firmware/ath6k/AR6003/hw2.1.1/bdata.bin:system/etc/firmware/ath6k/AR6003/hw2.1.1/bdata.bin \
	vendor/samsung/delos3geur/proprietary/etc/firmware/ath6k/AR6003/hw2.1.1/fw-4.bin:system/etc/firmware/ath6k/AR6003/hw2.1.1/fw-4.bin \
	vendor/samsung/delos3geur/proprietary/etc/firmware/yamato_pfp.fw:system/etc/firmware/yamato_pfp.fw \
	vendor/samsung/delos3geur/proprietary/etc/firmware/yamato_pfp.fw:system/etc/firmware/yamato_pm4.fw \
	vendor/samsung/delos3geur/proprietary/etc/wifi/wpa_supplicant.conf:system/etc/wifi/wpa_supplicant.conf \
	vendor/samsung/delos3geur/proprietary/etc/audio_effects.conf:system/etc/audio_effects.conf \
	vendor/samsung/delos3geur/proprietary/etc/audio_policy.conf:system/etc/audio_policy.conf \
	vendor/samsung/delos3geur/proprietary/etc/gps.conf:system/etc/gps.conf \
	vendor/samsung/delos3geur/proprietary/etc/thermald-8x25-msm1-pmic_therm.conf:system/etc/thermald-8x25-msm1-pmic_therm.conf \
	vendor/samsung/delos3geur/proprietary/etc/thermald-8x25-msm2-msm_therm.conf:system/etc/thermald-8x25-msm2-msm_therm.conf \
	vendor/samsung/delos3geur/proprietary/etc/thermald-8x25-msm2-pmic_therm.conf:system/etc/thermald-8x25-msm2-pmic_therm.conf \
	vendor/samsung/delos3geur/proprietary/etc/thermald-8x25q-msm2-msm_therm.conf:system/etc/thermald-8x25q-msm2-msm_therm.conf \
	vendor/samsung/delos3geur/proprietary/lib/egl/eglsubAndroid.so:system/lib/egl/eglsubAndroid.so \
	vendor/samsung/delos3geur/proprietary/lib/egl/libEGL_adreno200.so:system/lib/egl/libEGL_adreno200.so \
	vendor/samsung/delos3geur/proprietary/lib/egl/libGLESv1_CM_adreno200.so:system/lib/egl/libGLESv1_CM_adreno200.so \
	vendor/samsung/delos3geur/proprietary/lib/egl/libGLESv2_adreno200.so:system/lib/egl/libGLESv2_adreno200.so \
	vendor/samsung/delos3geur/proprietary/lib/egl/libq3dtools_adreno200.so:system/lib/egl/libq3dtools_adreno200.so \
        vendor/samsung/delos3geur/proprietary/lib/egl/libplayback_adreno200.so:system/lib/egl/libplayback_adreno200.so \
        vendor/samsung/delos3geur/proprietary/lib/egl/libGLESv2S3D_adreno200.so:system/lib/egl/libGLESv2S3D_adreno200.so \
	vendor/samsung/delos3geur/proprietary/lib/hw/camera.msm7x27a.so:system/lib/hw/camera.msm7x27a.so \
	vendor/samsung/delos3geur/proprietary/lib/hw/gps.msm7x27a.so:system/lib/hw/gps.msm7x27a.so \
	vendor/samsung/delos3geur/proprietary/lib/hw/lights.msm7x27a.so:system/lib/hw/lights.msm7x27a.so \
	vendor/samsung/delos3geur/proprietary/lib/hw/sensors.default.so:system/lib/hw/sensors.default.so \
	vendor/samsung/delos3geur/proprietary/lib/libaudiopolicy_sec.so:system/lib/libaudiopolicy_sec.so \
	vendor/samsung/delos3geur/proprietary/lib/libgemini.so:system/lib/libgemini.so \
	vendor/samsung/delos3geur/proprietary/lib/libgps.so:system/lib/libgps.so \
	vendor/samsung/delos3geur/proprietary/lib/libgps.utils.so:system/lib/libgps.utils.so \
	vendor/samsung/delos3geur/proprietary/lib/libgsl.so:system/lib/libgsl.so \
        vendor/samsung/delos3geur/proprietary/lib/libllvm-arm.so:system/lib/libllvm-arm.so \
	vendor/samsung/delos3geur/proprietary/lib/libhwcexternal.so:system/lib/libhwcexternal.so \
	vendor/samsung/delos3geur/proprietary/lib/libhwcservice.so:system/lib/libhwcservice.so \
	vendor/samsung/delos3geur/proprietary/lib/libidl.so:system/lib/libidl.so \
	vendor/samsung/delos3geur/proprietary/lib/libimage-jpeg-enc-omx-comp.so:system/lib/libimage-jpeg-enc-omx-comp.so \
	vendor/samsung/delos3geur/proprietary/lib/libimage-omx-common.so:system/lib/libimage-omx-common.so \
	vendor/samsung/delos3geur/proprietary/lib/libloc_adapter.so:system/lib/libloc_adapter.so \
	vendor/samsung/delos3geur/proprietary/lib/libloc_api_v02.so:system/lib/libloc_api_v02.so \
	vendor/samsung/delos3geur/proprietary/lib/libloc_eng.so:system/lib/libloc_eng.so \
	vendor/samsung/delos3geur/proprietary/lib/libmmcamera_faceproc.so:system/lib/libmmcamera_faceproc.so \
	vendor/samsung/delos3geur/proprietary/lib/libmmcamera_frameproc.so:system/lib/libmmcamera_frameproc.so \
	vendor/samsung/delos3geur/proprietary/lib/libmmcamera_hdr_lib.so:system/lib/libmmcamera_hdr_lib.so \
	vendor/samsung/delos3geur/proprietary/lib/libmmcamera_image_stab.so:system/lib/libmmcamera_image_stab.so \
	vendor/samsung/delos3geur/proprietary/lib/libmmcamera_interface2.so:system/lib/libmmcamera_interface2.so \
	vendor/samsung/delos3geur/proprietary/lib/libmmcamera_statsproc31.so:system/lib/libmmcamera_statsproc31.so \
	vendor/samsung/delos3geur/proprietary/lib/libmmcamera_wavelet_lib.so:system/lib/libmmcamera_wavelet_lib.so \
	vendor/samsung/delos3geur/proprietary/lib/libmmipl.so:system/lib/libmmipl.so \
	vendor/samsung/delos3geur/proprietary/lib/libmmjpeg.so:system/lib/libmmjpeg.so \
	vendor/samsung/delos3geur/proprietary/lib/libmm-color-convertor.so:system/lib/libmm-color-convertor.so \
	vendor/samsung/delos3geur/proprietary/lib/libmmstillomx.so:system/lib/libmmstillomx.so \
	vendor/samsung/delos3geur/proprietary/lib/libnetmgr.so:system/lib/libnetmgr.so \
	vendor/samsung/delos3geur/proprietary/lib/libOmxAacDec.so:system/lib/libOmxAacDec.so \
	vendor/samsung/delos3geur/proprietary/lib/libOmxAacEnc.so:system/lib/libOmxAacEnc.so \
	vendor/samsung/delos3geur/proprietary/lib/libOmxAc3HwDec.so:system/lib/libOmxAc3HwDec.so \
	vendor/samsung/delos3geur/proprietary/lib/libOmxAdpcmDec.so:system/lib/lbOmxAdpcmDec.so \
	vendor/samsung/delos3geur/proprietary/lib/libOmxAmrDec.so:system/lib/libOmxAmrDec.so \
	vendor/samsung/delos3geur/proprietary/lib/libOmxAmrEnc.so:system/lib/libOmxAmrEnc.so \
	vendor/samsung/delos3geur/proprietary/lib/libOmxAmrRtpDec.so:system/lib/libMxAmrRtpDec.so \
	vendor/samsung/delos3geur/proprietary/lib/libOmxAmrwbDec.so:system/lib/libOmxAmrwbDec.so \
	vendor/samsung/delos3geur/proprietary/lib/libOmxCore.so:system/lib/libOmxCore.so \
	vendor/samsung/delos3geur/proprietary/lib/libOmxEvrcDec.so:system/lib/libOmxEvrcDec.so \
	vendor/samsung/delos3geur/proprietary/lib/libOmxEvrcEnc.so:system/lib/libOmxEvrcEnc.so \
	vendor/samsung/delos3geur/proprietary/lib/libOmxEvrcHwDec.so:system/lib/libOmxEvrcHwDec.so \
	vendor/samsung/delos3geur/proprietary/lib/libOmxH264Dec.so:system/lib/libOmxH264Dec.so \
	vendor/samsung/delos3geur/proprietary/lib/libOmxIttiamVdec.so:system/lib/libOmxIttiamVdec.so \
	vendor/samsung/delos3geur/proprietary/lib/libOmxIttiamVenc.so:system/lib/libOmxIttiamVenc.so \
	vendor/samsung/delos3geur/proprietary/lib/libOmxMp3Dec.so:system/lib/libOmxMp3Dec.so \
	vendor/samsung/delos3geur/proprietary/lib/libOmxMpeg4Dec.so:system/lib/libOmxMpeg4Dec.so \
	vendor/samsung/delos3geur/proprietary/lib/libOmxOn2Dec.so:system/lib/libOmxOn2Dec.so \
	vendor/samsung/delos3geur/proprietary/lib/libOmxQcelp13Dec.so:system/lib/libOmxQcelp13Dec.so \
	vendor/samsung/delos3geur/proprietary/lib/libOmxQcelp13Enc.so:system/lib/libOmxQcelp13Enc.so \
	vendor/samsung/delos3geur/proprietary/lib/libOmxQcelpHwDec.so:system/lib/libOmxQcelpHwDec.so \
	vendor/samsung/delos3geur/proprietary/lib/libOmxVidEnc.so:system/lib/libOmxVidEnc.so \
	vendor/samsung/delos3geur/proprietary/lib/libOmxVp8Dec.so:system/lib/libOmxVp8Dec.so \
	vendor/samsung/delos3geur/proprietary/lib/libOmxWmaDec.so:system/lib/libOmxWmaDec.so \
	vendor/samsung/delos3geur/proprietary/lib/libOmxWmvDec.so:system/lib/libOmxWmvDec.so \
	vendor/samsung/delos3geur/proprietary/lib/libOmxrv9Dec.so:system/lib/libOmxrv9Dec.so \
	vendor/samsung/delos3geur/proprietary/lib/libOpenVG.so:system/lib/libOpenVG.so \
        vendor/samsung/delos3geur/proprietary/lib/libOpenCL.so:system/lib/libOpenCL.so \
	vendor/samsung/delos3geur/proprietary/lib/libC2D2.so:system/lib/libC2D2.so \
	vendor/samsung/delos3geur/proprietary/lib/libc2d2_z180.so:system/lib/libc2d2_z180.so \
	vendor/samsung/delos3geur/proprietary/lib/libchromatix_imx074_default_video.so:system/lib/libchromatix_imx074_default_video.so \
	vendor/samsung/delos3geur/proprietary/lib/libchromatix_imx074_preview.so:system/lib/libchromatix_imx074_preview.so \
	vendor/samsung/delos3geur/proprietary/lib/libchromatix_imx074_video_hd.so:system/lib/libchromatix_imx074_video_hd.so \
	vendor/samsung/delos3geur/proprietary/lib/libchromatix_imx074_zsl.so:system/lib/libchromatix_imx074_zsl.so \
	vendor/samsung/delos3geur/proprietary/lib/libchromatix_imx091_default_video.so:system/lib/libchromatix_imx091_default_video.so \
	vendor/samsung/delos3geur/proprietary/lib/libchromatix_imx091_preview.so:system/lib/libchromatix_imx091_preview.so \
	vendor/samsung/delos3geur/proprietary/lib/libchromatix_imx091_video_hd.so:system/lib/libchromatix_imx091_video_hd.so \
	vendor/samsung/delos3geur/proprietary/lib/libchromatix_ov2720_default_video.so:system/lib/libchromatix_ov2720_default_video.so \
	vendor/samsung/delos3geur/proprietary/lib/libchromatix_ov2720_hfr.so:system/lib/libchromatix_ov2720_hfr.so \
	vendor/samsung/delos3geur/proprietary/lib/libchromatix_ov2720_preview.so:system/lib/libchromatix_ov2720_preview.so \
	vendor/samsung/delos3geur/proprietary/lib/libchromatix_ov2720_zsl.so:system/lib/libchromatix_ov2720_zsl.so \
	vendor/samsung/delos3geur/proprietary/lib/libchromatix_ov5647_preview.so:system/lib/libchromatix_ov5647_preview.so \
	vendor/samsung/delos3geur/proprietary/lib/libchromatix_s5k3l1yx_default_video.so:system/lib/libchromatix_s5k3l1yx_default_video.so \
	vendor/samsung/delos3geur/proprietary/lib/libchromatix_s5k3l1yx_hfr_120fps.so:system/lib/libchromatix_s5k3l1yx_hfr_120fps.so \
	vendor/samsung/delos3geur/proprietary/lib/libchromatix_s5k3l1yx_hfr_60fps.so:system/lib/libchromatix_s5k3l1yx_hfr_60fps.so \
	vendor/samsung/delos3geur/proprietary/lib/libchromatix_s5k3l1yx_hfr_90fps.so:system/lib/libchromatix_s5k3l1yx_hfr_90fps.so \
	vendor/samsung/delos3geur/proprietary/lib/libchromatix_s5k3l1yx_preview.so:system/lib/libchromatix_s5k3l1yx_preview.so \
	vendor/samsung/delos3geur/proprietary/lib/libchromatix_s5k3l1yx_video_hd.so:system/lib/libchromatix_s5k3l1yx_video_hd.so \
	vendor/samsung/delos3geur/proprietary/lib/libchromatix_s5k3l1yx_zsl.so:system/lib/libchromatix_s5k3l1yx_zsl.so \
	vendor/samsung/delos3geur/proprietary/lib/libsecnativefeature.so:system/lib/libsecnativefeature.so \
	vendor/samsung/delos3geur/proprietary/lib/libc2d2_z180.so:system/lib/libc2d2_z180.so \
	vendor/samsung/delos3geur/proprietary/lib/libqdi.so:system/lib/libqdi.so \
	vendor/samsung/delos3geur/proprietary/lib/libqdp.so:system/lib/libqdp.so \
	vendor/samsung/delos3geur/proprietary/lib/libqmi.so:system/lib/libqmi.so \
	vendor/samsung/delos3geur/proprietary/lib/libqmi_client_qmux.so:system/lib/libqmi_client_qmux.so \
	vendor/samsung/delos3geur/proprietary/lib/libril-qc-qmi-1.so:system/lib/libril-qc-qmi-1.so
