# Copyright (C) 2011-2013 The CyanogenMod Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/samsung/delos3geur/setup-makefiles.sh

VENDOR := vendor/samsung/delos3geur/proprietary

PRODUCT_COPY_FILES += \
	$(VENDOR)/bin/btnvtool:system/bin/btnvtool \
	$(VENDOR)/bin/ds_fmc_appd:system/bin/ds_fmc_appd \
	$(VENDOR)/bin/e2fsck:system/bin/e2fsck \
	$(VENDOR)/bin/fmconfig:system/bin/fmconfig \
	$(VENDOR)/bin/hci_qcomm_init:system/bin/hci_qcomm_init \
	$(VENDOR)/bin/keystore:system/bin/keystore \
	$(VENDOR)/bin/mpdecision:system/bin/mpdecision \
	$(VENDOR)/bin/netmgrd:system/bin/netmgrd \
	$(VENDOR)/bin/qmuxd:system/bin/qmuxd \
	$(VENDOR)/bin/rmt_storage:system/bin/rmt_storage \
	$(VENDOR)/bin/thermald:system/bin/thermald \
	$(VENDOR)/bin/usbhub:system/bin/usbhub \
	$(VENDOR)/bin/usbhub_init:system/usbhub_init \
	$(VENDOR)/etc/firmware/ath6k/AR6003/hw2.1.1/athtcmd_ram.bin:system/etc/firmware/ath6k/AR6003/hw2.1.1/athtcmd_ram.bin \
	$(VENDOR)/etc/firmware/ath6k/AR6003/hw2.1.1/bdata.bin:system/etc/firmware/ath6k/AR6003/hw2.1.1/bdata.bin \
	$(VENDOR)/etc/firmware/ath6k/AR6003/hw2.1.1/fw-4.bin:system/etc/firmware/ath6k/AR6003/hw2.1.1/fw-4.bin \
	$(VENDOR)/etc/firmware/yamato_pfp.fw:system/etc/firmware/yamato_pfp.fw \
	$(VENDOR)/etc/firmware/yamato_pfp.fw:system/etc/firmware/yamato_pm4.fw \
	$(VENDOR)/etc/wifi/wpa_supplicant.conf:system/etc/wifi/wpa_supplicant.conf \
	$(VENDOR)/etc/audio_effects.conf:system/etc/audio_effects.conf \
	$(VENDOR)/etc/audio_policy.conf:system/etc/audio_policy.conf \
	$(VENDOR)/etc/gps.conf:system/etc/gps.conf \
	$(VENDOR)/etc/thermald-8x25-msm1-pmic_therm.conf:system/etc/thermald-8x25-msm1-pmic_therm.conf \
	$(VENDOR)/etc/thermald-8x25-msm2-msm_therm.conf:system/etc/thermald-8x25-msm2-msm_therm.conf \
	$(VENDOR)/etc/thermald-8x25-msm2-pmic_therm.conf:system/etc/thermald-8x25-msm2-pmic_therm.conf \
	$(VENDOR)/etc/thermald-8x25q-msm2-msm_therm.conf:system/etc/thermald-8x25q-msm2-msm_therm.conf \
	$(VENDOR)/lib/egl/eglsubAndroid.so:system/lib/egl/eglsubAndroid.so \
	$(VENDOR)/lib/egl/libEGL_adreno200.so:system/lib/egl/libEGL_adreno200.so \
	$(VENDOR)/lib/egl/libGLESv1_CM_adreno200.so:system/lib/egl/libGLESv1_CM_adreno200.so \
	$(VENDOR)/lib/egl/libGLESv2_adreno200.so:system/lib/egl/libGLESv2_adreno200.so \
	$(VENDOR)/lib/egl/libq3dtools_adreno200.so:system/lib/egl/libq3dtools_adreno200.so \
	$(VENDOR)/lib/hw/camera.msm7x27a.so:system/lib/hw/camera.msm7x27a.so \
	$(VENDOR)/lib/hw/gps.msm7x27a.so:system/lib/hw/gps.msm7x27a.so \
	$(VENDOR)/lib/hw/lights.msm7x27a.so:system/lib/hw/lights.msm7x27a.so \
	$(VENDOR)/lib/hw/sensors.default.so:system/lib/hw/sensors.default.so \
	$(VENDOR)/lib/libaudiopolicy_sec.so:system/lib/libaudiopolicy_sec.so \
	$(VENDOR)/lib/libgemini.so:system/lib/libgemini.so \
	$(VENDOR)/lib/libgps.so:system/lib/libgps.so \
	$(VENDOR)/lib/libgps.utils.so:system/lib/libgps.utils.so \
	$(VENDOR)/lib/libgsl.so:system/lib/libgsl.so \
	$(VENDOR)/lib/libhwcexternal.so:system/lib/libhwcexternal.so \
	$(VENDOR)/lib/libhwcservice.so:system/lib/libhwcservice.so \
	$(VENDOR)/lib/libidl.so:system/lib/libidl.so \
	$(VENDOR)/lib/libimage-jpeg-enc-omx-comp.so:system/lib/libimage-jpeg-enc-omx-comp.so \
	$(VENDOR)/lib/libimage-omx-common.so:system/lib/libimage-omx-common.so \
	$(VENDOR)/lib/libloc_adapter.so:system/lib/libloc_adapter.so \
	$(VENDOR)/lib/libloc_api_v02.so:system/lib/libloc_api_v02.so \
	$(VENDOR)/lib/libloc_eng.so:system/lib/libloc_eng.so \
	$(VENDOR)/lib/libmmcamera_faceproc.so:system/lib/libmmcamera_faceproc.so \
	$(VENDOR)/lib/libmmcamera_frameproc.so:system/lib/libmmcamera_frameproc.so \
	$(VENDOR)/lib/libmmcamera_hdr_lib.so:system/lib/libmmcamera_hdr_lib.so \
	$(VENDOR)/lib/libmmcamera_image_stab.so:system/lib/libmmcamera_image_stab.so \
	$(VENDOR)/lib/libmmcamera_interface2.so:system/lib/libmmcamera_interface2.so \
	$(VENDOR)/lib/libmmcamera_statsproc31.so:system/lib/libmmcamera_statsproc31.so \
	$(VENDOR)/lib/libmmcamera_wavelet_lib.so:system/lib/libmmcamera_wavelet_lib.so \
	$(VENDOR)/lib/libmmipl.so:system/lib/libmmipl.so \
	$(VENDOR)/lib/libmmjpeg.so:system/lib/libmmjpeg.so \
	$(VENDOR)/lib/libmmstillomx.so:system/lib/libmmstillomx.so \
	$(VENDOR)/lib/libnetmgr.so:system/lib/libnetmgr.so \
	$(VENDOR)/lib/libOmxAacDec.so:system/lib/libOmxAacDec.so \
	$(VENDOR)/lib/libOmxAacEnc.so:system/lib/libOmxAacEnc.so \
	$(VENDOR)/lib/libOmxAc3HwDec.so:system/lib/libOmxAc3HwDec.so \
	$(VENDOR)/lib/libOmxAdpcmDec.so:system/lib/lbOmxAdpcmDec.so \
	$(VENDOR)/lib/libOmxAmrDec.so:system/lib/libOmxAmrDec.so \
	$(VENDOR)/lib/libOmxAmrEnc.so:system/lib/libOmxAmrEnc.so \
	$(VENDOR)/lib/libOmxAmrRtpDec.so:system/lib/libMxAmrRtpDec.so \
	$(VENDOR)/lib/libOmxAmrwbDec.so:system/lib/libOmxAmrwbDec.so \
	$(VENDOR)/lib/libOmxCore.so:system/lib/libOmxCore.so \
	$(VENDOR)/lib/libOmxEvrcDec.so:system/lib/libOmxEvrcDec.so \
	$(VENDOR)/lib/libOmxEvrcEnc.so:system/lib/libOmxEvrcEnc.so \
	$(VENDOR)/lib/libOmxEvrcHwDec.so:system/lib/libOmxEvrcHwDec.so \
	$(VENDOR)/lib/libOmxH264Dec.so:system/lib/libOmxH264Dec.so \
	$(VENDOR)/lib/libOmxIttiamVdec.so:system/lib/libOmxIttiamVdec.so \
	$(VENDOR)/lib/libOmxIttiamVenc.so:system/lib/libOmxIttiamVenc.so \
	$(VENDOR)/lib/libOmxMp3Dec.so:system/lib/libOmxMp3Dec.so \
	$(VENDOR)/lib/libOmxMpeg4Dec.so:system/lib/libOmxMpeg4Dec.so \
	$(VENDOR)/lib/libOmxOn2Dec.so:system/lib/libOmxOn2Dec.so \
	$(VENDOR)/lib/libOmxQcelp13Dec.so:system/lib/libOmxQcelp13Dec.so \
	$(VENDOR)/lib/libOmxQcelp13Enc.so:system/lib/libOmxQcelp13Enc.so \
	$(VENDOR)/lib/libOmxQcelpHwDec.so:system/lib/libOmxQcelpHwDec.so \
	$(VENDOR)/lib/libOmxVidEnc.so:system/lib/libOmxVidEnc.so \
	$(VENDOR)/lib/libOmxVp8Dec.so:system/lib/libOmxVp8Dec.so \
	$(VENDOR)/lib/libOmxWmaDec.so:system/lib/libOmxWmaDec.so \
	$(VENDOR)/lib/libOmxWmvDec.so:system/lib/libOmxWmvDec.so \
	$(VENDOR)/lib/libOmxrv9Dec.so:system/lib/libOmxrv9Dec.so \
	$(VENDOR)/lib/libchromatix_imx074_default_video.so:system/lib/libchromatix_imx074_default_video.so \
	$(VENDOR)/lib/libchromatix_imx074_preview.so:system/lib/libchromatix_imx074_preview.so \
	$(VENDOR)/lib/libchromatix_imx074_video_hd.so:system/lib/libchromatix_imx074_video_hd.so \
	$(VENDOR)/lib/libchromatix_imx074_zsl.so:system/lib/libchromatix_imx074_zsl.so \
	$(VENDOR)/lib/libchromatix_imx091_default_video.so:system/lib/libchromatix_imx091_default_video.so \
	$(VENDOR)/lib/libchromatix_imx091_preview.so:system/lib/libchromatix_imx091_preview.so \
	$(VENDOR)/lib/libchromatix_imx091_video_hd.so:system/lib/libchromatix_imx091_video_hd.so \
	$(VENDOR)/lib/libchromatix_ov2720_default_video.so:system/lib/libchromatix_ov2720_default_video.so \
	$(VENDOR)/lib/libchromatix_ov2720_hfr.so:system/lib/libchromatix_ov2720_hfr.so \
	$(VENDOR)/lib/libqdi.so:system/lib/libqdi.so \
	$(VENDOR)/lib/libqdp.so:system/lib/libqdp.so \
	$(VENDOR)/lib/libqmi.so:system/lib/libqmi.so \
	$(VENDOR)/lib/libqmi_client_qmux.so:system/lib/libqmi_client_qmux.so \
	$(VENDOR)/lib/libril-qc-qmi-1.so:system/lib/libril-qc-qmi-1.so
