# Copyright (C) 2011-2013 The CyanogenMod Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/samsung/delos3geur/setup-makefiles.sh

PRODUCT_COPY_FILES += \
	vendor/samsung/delos3geur/proprietary/bin/btnvtool:system/bin/btnvtool \
	vendor/samsung/delos3geur/proprietary/bin/ds_fmc_appd:system/bin/ds_fmc_appd \
	vendor/samsung/delos3geur/proprietary/bin/e2fsck:system/bin/e2fsck \
	vendor/samsung/delos3geur/proprietary/bin/fmconfig:system/bin/fmconfig \
	vendor/samsung/delos3geur/proprietary/bin/hci_qcomm_init:system/bin/hci_qcomm_init \
	vendor/samsung/delos3geur/proprietary/bin/keystore:system/bin/keystore \
	vendor/samsung/delos3geur/proprietary/bin/mpdecision:system/bin/mpdecision \
	vendor/samsung/delos3geur/proprietary/bin/netmgrd:system/bin/netmgrd \
	vendor/samsung/delos3geur/proprietary/bin/qmuxd:system/bin/qmuxd \
	vendor/samsung/delos3geur/proprietary/bin/rmt_storage:system/bin/rmt_storage \
	vendor/samsung/delos3geur/proprietary/bin/thermald:system/bin/thermald \
	vendor/samsung/delos3geur/proprietary/bin/usbhub:system/bin/usbhub \
	vendor/samsung/delos3geur/proprietary/bin/usbhub_init:system/usbhub_init \
	vendor/samsung/delos3geur/proprietary/etc/firmware/ath6k/AR6003/hw2.1.1/athtcmd_ram.bin:system/etc/firmware/ath6k/AR6003/hw2.1.1/athtcmd_ram.bin \
	vendor/samsung/delos3geur/proprietary/etc/firmware/ath6k/AR6003/hw2.1.1/bdata.bin:system/etc/firmware/ath6k/AR6003/hw2.1.1/bdata.bin \
	vendor/samsung/delos3geur/proprietary/etc/firmware/ath6k/AR6003/hw2.1.1/fw-4.bin:system/etc/firmware/ath6k/AR6003/hw2.1.1/fw-4.bin \
	vendor/samsung/delos3geur/proprietary/etc/firmware/yamato_pfp.fw:system/etc/firmware/yamato_pfp.fw \
	vendor/samsung/delos3geur/proprietary/etc/firmware/yamato_pfp.fw:system/etc/firmware/yamato_pm4.fw \
	vendor/samsung/delos3geur/proprietary/etc/wifi/wpa_supplicant.conf:system/etc/wifi/wpa_supplicant.conf \
	vendor/samsung/delos3geur/proprietary/etc/audio_effects.conf:system/etc/audio_effects.conf \
	vendor/samsung/delos3geur/proprietary/etc/audio_policy.conf:system/etc/audio_policy.conf \
	vendor/samsung/delos3geur/proprietary/etc/gps.conf:system/etc/gps.conf \
	vendor/samsung/delos3geur/proprietary/etc/thermald-8x25-msm1-pmic_therm.conf:system/etc/thermald-8x25-msm1-pmic_therm.conf \
	vendor/samsung/delos3geur/proprietary/etc/thermald-8x25-msm2-msm_therm.conf:system/etc/thermald-8x25-msm2-msm_therm.conf \
	vendor/samsung/delos3geur/proprietary/etc/thermald-8x25-msm2-pmic_therm.conf:system/etc/thermald-8x25-msm2-pmic_therm.conf \
	vendor/samsung/delos3geur/proprietary/etc/thermald-8x25q-msm2-msm_therm.conf:system/etc/thermald-8x25q-msm2-msm_therm.conf \
	vendor/samsung/delos3geur/proprietary/lib/egl/eglsubAndroid.so:system/lib/egl/eglsubAndroid.so \
	vendor/samsung/delos3geur/proprietary/lib/egl/libEGL_adreno200.so:system/lib/egl/libEGL_adreno200.so \
	vendor/samsung/delos3geur/proprietary/lib/egl/libGLES_android.so:system/lib/egl/libGLES_android.so \
	vendor/samsung/delos3geur/proprietary/lib/egl/libGLESv1_CM_adreno200.so:system/lib/egl/libGLESv1_CM_adreno200.so \
	vendor/samsung/delos3geur/proprietary/lib/egl/libGLESv2_adreno200.so:system/lib/egl/libGLESv2_adreno200.so \
	vendor/samsung/delos3geur/proprietary/lib/egl/libq3dtools_adreno200.so:system/lib/egl/libq3dtools_adreno200.so \
	vendor/samsung/delos3geur/proprietary/lib/hw/audio.primary.default.so:system/lib/hw/audio.primary.default.so \
	vendor/samsung/delos3geur/proprietary/lib/hw/audio.primary.msm7x27a.so:system/lib/hw/audio.primary.msm7x27a.so \
	vendor/samsung/delos3geur/proprietary/lib/hw/audio_policy.default.so:system/lib/hw/audio_policy.default.so \
	vendor/samsung/delos3geur/proprietary/lib/hw/audio_policy.msm7x27a.so:system/lib/hw/audio_policy.msm7x27a.so \
	vendor/samsung/delos3geur/proprietary/lib/hw/camera.msm7x27a.so:system/lib/hw/camera.msm7x27a.so \
	vendor/samsung/delos3geur/proprietary/lib/hw/gps.msm7x27a.so:system/lib/hw/gps.msm7x27a.so \
	vendor/samsung/delos3geur/proprietary/lib/hw/lights.msm7x27a.so:system/lib/hw/lights.msm7x27a.so \
	vendor/samsung/delos3geur/proprietary/lib/hw/sensors.delos3geur.so:system/lib/hw/sensors.delos3geur.so \
	vendor/samsung/delos3geur/proprietary/lib/libaudiopolicy_sec.so:system/lib/libaudiopolicy_sec.so \
	vendor/samsung/delos3geur/proprietary/lib/libC2D2.so:system/lib/libC2D2.so \
	vendor/samsung/delos3geur/proprietary/lib/libgemini.so:system/lib/libgemini.so \
	vendor/samsung/delos3geur/proprietary/lib/libgps.so:system/lib/libgps.so \
	vendor/samsung/delos3geur/proprietary/lib/libgps.utils.so:system/lib/libgps.utils.so \
	vendor/samsung/delos3geur/proprietary/lib/libgsl.so:system/lib/libgsl.so \
	vendor/samsung/delos3geur/proprietary/lib/libhwcexternal.so:system/lib/libhwcexternal.so \
	vendor/samsung/delos3geur/proprietary/lib/libhwcservice.so:system/lib/libhwcservice.so \
	vendor/samsung/delos3geur/proprietary/lib/libidl.so:system/lib/libidl.so \
	vendor/samsung/delos3geur/proprietary/lib/libimage-jpeg-enc-omx-comp.so:system/lib/libimage-jpeg-enc-omx-comp.so \
	vendor/samsung/delos3geur/proprietary/lib/libimage-omx-common.so:system/lib/libimage-omx-common.so \
	vendor/samsung/delos3geur/proprietary/lib/libloc_adapter.so:system/lib/libloc_adapter.so \
	vendor/samsung/delos3geur/proprietary/lib/libloc_api_v02.so:system/lib/libloc_api_v02.so \
	vendor/samsung/delos3geur/proprietary/lib/libloc_eng.so:system/lib/libloc_eng.so \
	vendor/samsung/delos3geur/proprietary/lib/libmmcamera_faceproc.so:system/lib/libmmcamera_faceproc.so \
	vendor/samsung/delos3geur/proprietary/lib/libmmcamera_frameproc.so:system/lib/libmmcamera_frameproc.so \
	vendor/samsung/delos3geur/proprietary/lib/libmmcamera_hdr_lib.so:system/lib/libmmcamera_hdr_lib.so \
	vendor/samsung/delos3geur/proprietary/lib/libmmcamera_image_stab.so:system/lib/libmmcamera_image_stab.so \
	vendor/samsung/delos3geur/proprietary/lib/libmmcamera_interface2.so:system/lib/libmmcamera_interface2.so \
	vendor/samsung/delos3geur/proprietary/lib/libmmcamera_statsproc31.so:system/lib/libmmcamera_statsproc31.so \
	vendor/samsung/delos3geur/proprietary/lib/libmmcamera_wavelet_lib.so:system/lib/libmmcamera_wavelet_lib.so \
	vendor/samsung/delos3geur/proprietary/lib/libmmipl.so:system/lib/libmmipl.so \
	vendor/samsung/delos3geur/proprietary/lib/libmmjpeg.so:system/lib/libmmjpeg.so \
	vendor/samsung/delos3geur/proprietary/lib/libmmstillomx.so:system/lib/libmmstillomx.so \
	vendor/samsung/delos3geur/proprietary/lib/libnetmgr.so:system/lib/libnetmgr.so \
	vendor/samsung/delos3geur/proprietary/lib/libqdi.so:system/lib/libqdi.so \
	vendor/samsung/delos3geur/proprietary/lib/libqdp.so:system/lib/libqdp.so \
	vendor/samsung/delos3geur/proprietary/lib/libqmi.so:system/lib/libqmi.so \
	vendor/samsung/delos3geur/proprietary/lib/libqmi_client_qmux.so:system/lib/libqmi_client_qmux.so \
	vendor/samsung/delos3geur/proprietary/lib/libril-qc-qmi-1.so:system/lib/libril-qc-qmi-1.so
